### ISSUE TITLE
Unable to start calysto_processing

### ISSUE THREAD

**Issue by jlrw** [Calysto/calysto_processing#10]
calypso jupiter doesn't appear in my notebook choices
I installed calypso and processing without a problem.
The environment variable must be tripping me up. I thought I added the variable, but I don't think the program knows I did so.
Can you be more explicit (step by step instructions) with how, exactly, to set up this variable and link it to the program? I'd appreciate the help.
Thank you

**Comment by dsblank** [comment]
The command `jupyter kernelspec list` will show you the kernels it knows about, and from there you can examine the `kernel.json` file for each kernel.
