### ISSUE TITLE
javascript error 'require is not defined' in Jupyter-lab

### ISSUE THREAD

**Issue by kurakuradave** [Calysto/calysto_processing#11]
Hi,

I'm getting an error when running processing code in Jupyter-lab: 
```
Javascript Error: require is not defined

Sketch #1:
```

But... things work just fine in Jupyter notebook... I could choose the Calysto Processing kernel and execute processing code and see the results on the notebook.

Any idea what went wrong? How to get it to work with jupyter-lab?

Here are my setup:
Jupyter-lab v0.35.1
Jupyter v4.3.0
Processing v3.4
Ubuntu 16.04

Pls let me know if you need any details, thx!

**Comment by dsblank** [comment]
Thanks for the report! Jupyter Lab is a complete rewrite of the Jupyter environment, so this is going to have to be reworked. It probably will require an associated mime-type to know what to do, as one can't just inject Javascript into the DOM as before. I don't currently have this on my TODO list, but maybe an interested party could refactor this.

**Comment by kslader8** [comment]
This is also an issue for users of snorkel for weak supervision. +1

**Comment by deeplook** [comment]
Any progress on this?

**Comment by ttklm20** [comment]
https://stackoverflow.com/questions/54442858/javascript-output-is-disabled-in-jupyterlab
