### ISSUE TITLE
Unable to get calysto-processing to work in Binder

### ISSUE THREAD

**Issue by celinelatulipe** [Calysto/calysto_processing#13]
I've successfully gotten calysto-processing to work in a jupyter notebook on my own Mac laptop - it's very cool. Thanks!
However, I'm trying to get it to work on [Binder](https://gke.mybinder.org/) and having no luck. When I put my notebook on github, and connect it in Binder, binder builds and launches, but Binder only has the python kernel installed. I'm unsure of how to tell Binder to use calysto-processing. Any ideas on how to do this? I'm new to Binder, and although I've looked at all their [configuration files](https://mybinder.readthedocs.io/en/latest/config_files.html), I am lost on which configuration file to use and what to put in it to make calysto-processing work. 
<img width="1187" alt="calysto-processing-binder" src="https://user-images.githubusercontent.com/52825754/61174477-91a4e800-a56e-11e9-8687-2a5925697b09.png">

**Comment by dsblank** [comment]
You'd need to instruct binder to do what is described in this README. Unfortunately, you may need to find some binder help. Good luck!
