### ISSUE TITLE
Processing.js has been discontinued

### ISSUE THREAD

**Issue by Pomax** [Calysto/calysto_processing#14]
Hi,

I noticed that this project was based on Processing.js and just thought I'd let you know that I discontinued Processing.js December 2018. If this project is still being maintained, that's probably something worth being aware of, although it looks like the code's not been touched for a few years, so it might be worth mentioning that the project's no longer actively maintained, and that Pjs was discontinued so is unlikely to be receive any updates?

**Comment by dsblank** [comment]
Thanks for the update. This still works (and probably used an early copy of Processing.js) so no problem. It makes a great environment for teaching. Thanks for all of your work! Many students benefited from this. Some things that made this even more useful: 

* integrated with Jupyter Notebooks
* the student's code was compiled by java before running to catch syntax errors
* ability to pause/restart the sketch/cell

Here is a sample lecture: https://jupyter.brynmawr.edu/services/public/dblank/CS110%20Intro%20to%20Computing/2017-Fall/Notebooks/05-Movement.ipynb
