### ISSUE TITLE
importした時の動作について

### ISSUE THREAD

**Issue by sakur0u0** [Calysto/calysto_processing#16]
importしたrandomでインスタンスが作成できませんが、これは固有の問題でしょうか？

```java
import java.util.Random;

void setup(){
  randomSeed( 0 );
  for( int i = 0; i < 5; i++){
    println(  random( 1.0f ) );
  }  

  println("-----------------------");

  Random  rs  =  new  Random( 0 );
  for( int i = 0; i < 5; i++){
    println(  rs.nextFloat() );
  }
}
void draw(){
}
```
-----------------------
Sketch #34 state: ReferenceError: Random is not defined

0.12706408696249127
0.4680652036331594
0.9058290123939514
0.6254248928744346
0.36673190584406257
-----------------------
ReferenceError: Random is not defined

PDEでは問題なく動作します。

**Comment by dsblank** [comment]
Calysto Processing uses the Java to JavaScript conversion to run in the browser, so general Java is not allowed.
