### ISSUE TITLE
how to install calysto_processing?

### ISSUE THREAD

**Issue by Guest007** [Calysto/calysto_processing#2]
Hi.
I'll try to do:
1. install calysto_processing (in virtualenv through pip and git)
2. point to processing-java
3. run `jupyter netbook`

And after that I can't find processing in New list. What I missed?

**Comment by dsblank** [comment]
Perhaps you need to use the --user flag when you install?

**Comment by Guest007** [comment]
for now (while installing 2.0.2 from pipy) it give me a chance to create new notebook. 
I start it like 

```
$ PROCESSING_JAVA=/home/myname/tmp/test/processing-2.2.1 jupyter notebook
```

But I've got an exception

```
FileNotFoundError: [Errno 2] No such file or directory: 'processing-java'
```

I'm sure, that processing-java lays in /home/myname/tmp/test/processing-2.2.1 
Why it's not working?

**Comment by dsblank** [comment]
If that directory is in your path, then it should work. But a more direct way is to put a link to it directly in the calysto_processing/kernel.json, like:

``` json
{"argv": ["/usr/bin/python3", "-m", "calysto_processing", "-f", "{connection_file}"], "display_name": "Calysto Processing", "env": {"PROCESSING_JAVA": "/home/myname/tmp/test/processing-2.2.1/processing-java"}, "language": "java", "name": "calysto_processing"}
```

**Comment by Guest007** [comment]
I place new file kernel.json near the kernel.py with this content, fix the path to python. But it is still not working.

**Comment by dsblank** [comment]
You get the same error? Can you paste it here?

**Comment by Guest007** [comment]
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/guest007/.pyenv/versions/common35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/guest007/.pyenv/versions/common35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "/home/guest007/.pyenv/versions/common35/lib/python3.5/site-packages/metakernel/_metakernel.py", line 323, in do_execute
    retval = self.do_execute_direct(code)
  File "/home/guest007/.pyenv/versions/common35/lib/python3.5/site-packages/calysto_processing/kernel.py", line 152, in do_execute_direct
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/guest007/.pyenv/versions/3.5.0/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/home/guest007/.pyenv/versions/3.5.0/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'processing-java'
```

**Comment by dsblank** [comment]
If you edited the correct kernel.json file, I don't think you would get that error. It would instead try to run /home/myname/tmp/test/processing-2.2.1/processing-java

**Comment by Guest007** [comment]
I puted your string of json into empty kernel.json, touched by hands. May be I miss the original file, but it's not present in this repo

**Comment by dsblank** [comment]
It is not preset in the repo, but gets generated when you install. See setup.py for details. It should install it in the jupyter/ipython kernel spec location

**Comment by Guest007** [comment]
Thanks a lot! At last all parts of puzzle in right places!
