### ISSUE TITLE
Error No library found for processing.table

### ISSUE THREAD

**Issue by dougnukem** [Calysto/calysto_processing#3]
I've trying to install calysto_processing in my own local Mac OSX Jupyter installation.

I've done the following:

Installed Calysto-processing:

```
sudo -H pip3 install metakernel
sudo -H pip3 install calysto
sudo -H pip3 install --upgrade calysto-processing
```

Downloaded Processing 2.2.1 for OSX:
- http://download.processing.org/processing-2.2.1-macosx.zip
- installed `processing-java` tool

Then when I ran Jupyter and created a new Calysto-Processing notebook to run the example:
`jupyter notebook`
- [calysto_processing_example.ipynb](https://gist.github.com/dougnukem/bf00d989a7f5e5591336)

```
import processing.table.*;

Table table;

void setup() {
    table = loadTable("test.csv", "header");
    println(table.getRowCount() + " total rows in table"); 
}

long findMax() {
    int retval = 0;
    for (TableRow row : table.rows()) {
        int pop = row.getInt("Population");
        if (pop > retval)
            retval = pop;
    }
    return retval;
}
```

I got an error:

```
No library found for processing.table
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.
 Line     +---------------------------------------------------------------------------
    1:    | import processing.table.*;
    2:    | 
    3:    | Table table;
          +---------------------------------------------------------------------------

Compile error in line 0: The package “processing.table” does not exist. You might be missing a library.

```

**Comment by dsblank** [comment]
Oops... thanks for the report! Fixed documentation with 9e0d047050c8

**Comment by dougnukem** [comment]
Thanks for the quick response, I had to tweak it a little bit more:
- Generate the `test.csv`

```
%%file test.csv
"State","Population"
TX,4708708
AL,698473
AZ,6595778
TX,6595779
```
- change:
  - `pop = row.getInt("Population");`
  - `int pop = row.getInt("Population");`

Updated notebook gist: https://gist.github.com/dougnukem/bf00d989a7f5e5591336

**Comment by dsblank** [comment]
Good catch! I fixed the missing `int` and added a place to put sample notebooks:

https://github.com/Calysto/calysto_processing/tree/master/notebooks

where I added your gist, and removed identifying info.

**Comment by dsblank** [comment]
Thanks!
