### ISSUE TITLE
Installation documentation update

### ISSUE THREAD

**Issue by mdsw** [Calysto/calysto_processing#4]
In README.md, I believe "Edit the install calysto_processing/kernel.js to point processing_java." would be clearer as "Edit the installed calysto_processing/kernel.json to point to the processing_java command line tool". Additionally, you may want to add a note for Mac users that processing_java is not installed by default, but rather needs to be installed from the Processing environment by selecting 'Install "processing_java"' under the Tools menu.

**Comment by sspickle** [comment]
So I guess I'm pretty clueless here. Where is calysto_processing/kernel.json supposed to be? I'm on a Mac running "homebrew" python. I don't see it in

aluminum:~ steve$ find  /usr/local/lib/python2.7/site-packages/calysto_processing
/usr/local/lib/python2.7/site-packages/calysto_processing
/usr/local/lib/python2.7/site-packages/calysto_processing/**init**.py
/usr/local/lib/python2.7/site-packages/calysto_processing/**init**.pyc
/usr/local/lib/python2.7/site-packages/calysto_processing/**main**.py
/usr/local/lib/python2.7/site-packages/calysto_processing/**main**.pyc
/usr/local/lib/python2.7/site-packages/calysto_processing/kernel.py
/usr/local/lib/python2.7/site-packages/calysto_processing/kernel.pyc

or in ,ipython or .jupyter. 

Is there an easy way to identify the path I should be using here?

thanks,
-steve

**Comment by mdsw** [comment]
/usr/local/share/jupyter/kernels/calysto_processing/

**Comment by dsblank** [comment]
Thank you both for the feedback. I have updated the README.md a bit. Please see if that helps.

**Comment by blink1073** [comment]
Cool, I just found this:

``` bash
$ jupyter-kernelspec list
Available kernels:
  python3            /Users/ssilvester/anaconda/lib/python3.4/site-packages/ipykernel/resources
  calysto_scheme     /usr/local/share/jupyter/kernels/calysto_scheme
  matlab_kernel      /usr/local/share/jupyter/kernels/matlab_kernel
  metakernel_bash    /usr/local/share/jupyter/kernels/metakernel_bash
  octave_kernel      /usr/local/share/jupyter/kernels/octave_kernel
  xonsh_kernel       /usr/local/share/jupyter/kernels/xonsh_kernel
```
