### ISSUE TITLE
Python Mode for Processing

### ISSUE THREAD

**Issue by gcbgit** [Calysto/calysto_processing#5]
Calysto Processing is a fantastic way to bring interactive canvases to Jupyter.  Is there a way to enable Processing's Python Mode?

Ideally I'd love to be able to continue using the IPython kernel for R&D as I have been, but have access to the interactive and animated canvases of Processing.

**Comment by tildebyte** [comment]
iirc some work has been done on this, leveraging the very cool [Skulpt](https://github.com/skulpt) and the unfortunate [Processing.js](http://processingjs.org) as the back end, but I haven't been able to look at it in almost a year, so I don't know where things stand now.

**Comment by dsblank** [comment]
Yes, true, I should have mentioned that too (I wrote most of it.)  I'm not convinced Skulpt is going to be a good alternative in the long run as a complete Python in the browser. It is just too big of a problem.

I'm leaning in a different direction: use a real Python with a Processing-like library (there are a few). Then you get all of the benefits of Python, and can combine Processing with other libraries.

Or, going with a Jython kernel, and just make the processing library available. Then you get all of Java, too.

**Comment by gcbgit** [comment]
I just got a little more sophisticated in my sketch and Processing.py reminded me that it's only a thin veneer over Java and therefore can't import libraries like Numpy.  I'm starting to think that second idea of using a real Python with a Processing-like library is the better idea.

For my uses, what makes Processing magic is that I can just write a draw() routine and _boom_ interactivity!  Matplotlib has an animation capability, but it's far from interactive.  Maybe what I'm looking for is a way to spawn a thread or process that iterates around a given function call such as draw() and gives me a notebook widget that handles the drawing and mouse input (maybe through callbacks).  I'd prefer it not lock up the rest of the notebook while it's running.  It would be great it if was able to react to code changes in cells, but that might be too much to ask of Python and the GIL-- perhaps easiest to just clone the current notebook environment and force a restart when you want to incorporate changes elsewhere in the notebook.

I'm not clear on all the plumbing here, so I may be way off.

**Comment by dsblank** [comment]
@gcbgit I think this can be easier than you imagine. I think the right solution is to build a new Processing-like library for Python, taking advantage of Jupyter.

I've started a general graphics library with similar goals, but wasn't thinking about making it exactly compatible with Processing. (I needed a general graphics library for Python + Jupyter). It is here:

https://github.com/Calysto/calysto

If you were interested in making a fairly accurate version for Processing, I'd be interested in helping. I have starting to do that with John Zelle's graphics.py, so that students can use his book in Jupyter.

**Comment by tildebyte** [comment]
If you mean something that's kind of source-compatible with Processing.py, then sign me up for testing. I'd volunteer for JS, but it's not my gig.

**Comment by dsblank** [comment]
[This was the comment I originally meant to send.]

Perhaps, but I think it would be a different type of kernel. Calysto Processing does compile the Java code, but only to give good error messages. In the end, it throws away the compiled Java and then goes directly to JavaScript.

The Python mode (as I understand it) uses Jython. It could probably be done, but would be a kernel based on Java, or Jython.

**Comment by gcbgit** [comment]
I'm not sure if an exact match to Processing is important to my particular use case.  I use Jupyter/IPython as a modernized engineering notebook.  Mixing well formatted text with Sympy/Scipy/Matplotlib and the availability of libraries for more complex work (OpenCV, OpenCL) makes a great environment to pursue and document an analysis.  So, I've been standardizing on Python for my analysis language (rather than, say, Matlab).

Processing makes a good environment for simulation and interaction.  Including that capability into the lab notebook concept could be quite powerful.  To do that, it would help if it were Python based, and if it were able to draw upon information in earlier cells.  

The real beauty of Processing, in my view, is that it hides the complexity of the run loop.  The setup()/draw() paradigm is quite elegant.  This is the part I'm most interested in having access to within Jupyter.  Matplotlib is static, Processing is dynamic.

Processing also offers the promise of 3D visualization in a way that I haven't yet found available in Jupyter.

The other features of Processing aren't all that important to my particular use case.  Python already allows unstructured scripts.  The Processing preprocessor idea makes the syntax inconsistent in ways that I sometimes found awkward in Java-- but probably is less of a problem in Python as well.

The one real advantage I see to maintaining Processing compatibility is being able to take advantage of Processing's compiler to create faster sketches, or cross platform / stand alone executables.

I'll look through the Calysto stuff (I already make use of the Calysto spell checker).  A good drawing library separate from Matplotlib is welcome.  Unfortunately I think the Jupyter integration part of a dynamic canvas requires more Javascript and browser familiarity than I have.

**Comment by tildebyte** [comment]
I think what I was trying to get across was the idea of something which would be Python code entered into a Jupyter Python notebook which would just happen to look exactly like Procesing.py _at the source level_. The backend is immaterial to me, and I think to @gcbgit as well.
Whether this is some frankenstein's monster of Javascript + Python, a Python implementation of Processing... not my realm of expertise.

**Comment by gcbgit** [comment]
@tildebyte: just to understand your needs, why is source compatibility important to you?

**Comment by tildebyte** [comment]
Like you, I really like the "way of Processing". Processing.py -- being able to "do" Processing using Python -- was like finding the holy grail for me. Being able to take the existing sketches I have and drop them into a Python-native environment like Jupyter (with minimal changes) - priceless.

My other option is P5.js, an incredibly amazingly cool thing, which unfortunately involves learning Javascript, which imho is the ugliest programming language ever created (and I've studied quite a few).

**Comment by dsblank** [comment]
I'll be looking at P5 this summer, to develop a nice Jupyter environment for coding in that. 

BTW, using TypeScript rather than plain JavaScript makes JavaScript a much nicer language. I'll probably look at that as well.

**Comment by keithohara** [comment]
p5's render.js might be a quick and easy way to support p5 in the notebooks.

https://github.com/processing/p5.js/wiki/Embedding-p5.js

**Comment by tildebyte** [comment]
I've looked at TypeScript and CoffeeScript a little. I think I prefer Coffee. The only problem that I have with solutions like those is that the infrastructure isn't _as_ robust as either JS or Python (things like linters, syntax highlighters - the mundane but necessary tools which make life easier).

**Comment by dsblank** [comment]
TypeScript is to become part of the JS language, I think. That should help.

iframe's can be tricky... need to figure out why cross-scripting commands prevent it from working on Jupyterhub...

**Comment by dsblank** [comment]
Closing this issue (as it lists many ideas). Please re-open a specific issue, especially if you have a Pull Request implementing ideas. Thanks all!

(Updated Calysto Processing install code and instructions to make it easier to use)
