### ISSUE TITLE
no kernel.js?

### ISSUE THREAD

**Issue by sorenpraestegaard** [Calysto/calysto_processing#6]
Hi.

I am trying to install calysto-processing with the command "pip install --upgrade calysto-processing", as advised in README.MD. Everything looks good, all dependencies are good, so I assume that the installation is OK.

Continuing to the next step, I now have to "edit the installed calysto_processing/kernel.js to include the full path to the processing_java command." but I don't seem to have any kernel.js file on my system. Where should I look for that? I can't find any calysto_processing folder either.

When I start jupyter, I can still only make python notebooks.

(I am using anaconda3 on windows, if that makes any difference)

Sorry if this is not the right place for this, I tried to find another place for support, but couldn't find any. Please redirect me, if such a place exists!

Thank you for your help.

**Comment by sorenpraestegaard** [comment]
I can see that my issue is similar to this previously closed issue: https://github.com/Calysto/calysto_processing/issues/2

Looking through it now...

**Comment by dsblank** [comment]
I'm going to rewrite the installer to match the other updated calysto kernels this summer. Then it will be able to be installed more easily. Sorry for the complications!

**Comment by dsblank** [comment]
Installer rewritten. Try new instructions (see README.md).
