### ISSUE TITLE
ImportError: kernel

### ISSUE THREAD

**Issue by gngdb** [Calysto/calysto_processing#7]
I'm trying to install this in a fresh conda environment with just Jupyter installed, which leads to [this exported spec](https://gist.github.com/gngdb/45fce8f9993e992ab43cfb8be2d16e75). Running the pip command.

```
pip install --upgrade calysto-processing
```

When I do this, I get a series of errors, [log gist here](https://gist.github.com/gngdb/88e85d0a3fc5f875c4c24c050dc90674), and it looks like the install has failed at a glance. But, when I tried to install again, I realised it had actually left something in site-packages. I haven't finished the rest of the install and run the Jupyter server to see if it's actually working, but I'd rather get rid of the errors before continuing.

**Comment by dsblank** [comment]
Thanks for the note... I'll take a look.

**Comment by gngdb** [comment]
If I clone and run `pip install --upgrade -e .`, I get a strange problem where it reports that everything is installed:

```
Successfully installed IPython backports.shutil-get-terminal-size calysto-processing decorator enum34 html2text metakernel pathlib2 pexpect pickleshare prompt-toolkit ptyprocess pygments setuptools traitlets wcwidth
```

But then immediately hits an OSError:

```
OSError: [Errno 2] No such file or directory: '/opt/conda/envs/python2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg'
```

Similar to [this problem](http://stackoverflow.com/questions/34264512/error-setuptools-when-installing-tensorflow), so tried using `pip install --upgrade --ignore-installed -e .` and it runs without the final OSError.

**Comment by gngdb** [comment]
Although, a problem with doing it this way appears to be that no `kernel.js` is installed. I can write my own, which is what I've done, using the one in the documentation. After that, I tried to install the kernel with `jupyter kernelspec install`, and it reported success, but there are no new kernels in my Jupyter server.

**Comment by dsblank** [comment]
Updated install code and instructions.
