### ISSUE TITLE
Can't uninstall calysto_processing from jupyter notebooks

### ISSUE THREAD

**Issue by lvwarren** [Calysto/calysto_processing#9]
I was looking for a way to run "**Processing in Python**" scripts out of **Jupyter** notebooks so
I installed **calysto_processing** according to the instructions. When I figured out that it was instead wanting **Javascript** I tried removing it but I could not scrub the reference from the Jupyter notebook menu **New-->Calysto Processing**, shown below.

I tried uninstalling all the packages that **conda** and **pip** had listed, but the reference still wouldn't disappear. This took all evening. Any ideas? Thanks.
![screen shot 2018-04-16 at 10 35 31 pm](https://user-images.githubusercontent.com/589358/38847296-902721c6-41c6-11e8-92f3-23b475bdeba3.png)

**Comment by dsblank** [comment]
This kernel, like all Jupyter kernels, creates a JSON file in a Jupyter data directory. You can see where these directories are by issuing the command:

```
jupyter --paths
```

Under the `data:` section you will see one or more directories. In each, you can look for a `kernels` folder. The `kernels` folder contains a folder named `calysto_processing`. Delete that folder. 

As to your original goal, you might find useful [Skulpt Python](https://github.com/Calysto/skulpt_python) (uses a Python written in JavaScript), or perhaps [ICalico](http://wiki.roboteducation.org/ICalico) (uses IronPython to load a Processing.dll). I also believe that there is a pure-python Processing library that you could use from regular IPython.

**Comment by lvwarren** [comment]
Awesome response, Thanks.
